version: '3.7'

services:
  flask-prod:
    build:
      context: .
      target: production
    command: ./boot.sh
    restart: unless-stopped
    volumes:
      - ./:/app
    image: "mobileburd-production"
    ports:
      - '5006:80'
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info

